return {
  -- {
  --   "milanglacier/minuet-ai.nvim",
  --   dependencies = {
  --     "nvim-lua/plenary.nvim",
  --     "saghen/blink.cmp",
  --   },
  --   opts = {
  --     debug = true,
  --     provider = "openai_fim_compatible",
  --     n_completions = 1, -- recommend for local model for resource saving
  --     -- I recommend beginning with a small context window size and incrementally
  --     -- expanding it, depending on your local computing power. A context window
  --     -- of 512, serves as an good starting point to estimate your computing
  --     -- power. Once you have a reliable estimate of your local computing power,
  --     -- you should adjust the context window to a larger value.
  --     context_window = 512,
  --     provider_options = {
  --       openai_fim_compatible = {
  --         -- For Windows users, TERM may not be present in environment variables.
  --         -- Consider using APPDATA instead.
  --         api_key = "",
  --         name = "Ollama",
  --         end_point = "http://localhost:11434/api/generate", -- Correct endpoint for Ollama
  --         model = "deepcoder", -- Just the model name, no need for ":1.5b"
  --         optional = {
  --           max_tokens = 56,
  --           top_p = 0.9,
  --           temperature = 0.7, -- You might want to add this
  --         },
  --       },
  --     },
  --   },
  --   {
  --     "saghen/blink.cmp",
  --     dependencies = {
  --       "milanglacier/minuet-ai.nvim", -- Ensure minuet loads first
  --     },
  --     opts = {
  --       sources = {
  --         compat = { "minuet" },
  --         providers = {
  --           minuet = {
  --             name = "minuet",
  --             module = "minuet.blink",
  --             async = true,
  --             -- Should match minuet.config.request_timeout * 1000,
  --             -- since minuet.config.request_timeout is in seconds
  --             timeout_ms = 3000,
  --             score_offset = 50,
  --           },
  --         },
  --       },
  --     },
  --   },
  -- },
}
